### ISSUE TITLE
Bug stopping app

### ISSUE THREAD

**Issue by Stu75e** [guysoft/midistrum#2] opened 2023-09-30 14:36 UTC
When I click on the settings menu, the program stops

**Comment by Oktayey** [comment] 2023-09-30 18:20
Same. I'm on a Samsung Galaxy Note 9 running Android 10.

**Comment by guysoft** [comment] 2023-09-30 19:31
Can you provide the output of:
```sh
adb logcat python:I *:s
```
?

**Comment by Oktayey** [comment] 2023-10-01 15:56
I installed the newest release by manually downloading the APK, and opening the settings no longer crashes. Same device.

**Comment by guysoft** [comment] 2023-10-01 21:25
Downloading from the github or from f-droid?

It might be that your midi settings were taken somehow. The settings menu has the midi output setting. if its set to a taken device the app currently crashes.

**Comment by Oktayey** [comment] 2023-10-01 21:39
I downloaded from Github because the update isn't yet available on F-Droid.

**Comment by guysoft** [comment] 2023-10-01 21:49
Its the same build 0.27. The Github one is built using github actions and the f-droid one is built on f-droid server.
There might be minor changes in the build but its the same code.

I Just recently made sure that the apk is available here too.

**Comment by Oktayey** [comment] 2023-10-01 21:58
Oh, I mistakenly assumed yesterday's Github release was a new update that hadn't made it to F-Droid yet.

I uninstalled the Github build and reinstalled the F-Droid one, and it once again crashed.

**Comment by guysoft** [comment] 2023-10-01 22:20
hmm. Might be API versions difference between the builds. But I really cant tell without the adb logcat output

**Comment by guysoft** [comment] 2023-10-01 22:23
Managed to reproduce here. Will have a look tomorrow

**Comment by guysoft** [comment] 2023-10-05 11:16
Ok got the debug output:
```
1
10-05 14:15:32.838 18560 18591 I python  : 0
10-05 14:15:35.071 18560 18591 I python  : [INFO   ] [Base        ] Leaving application in progress...
10-05 14:15:35.071 18560 18591 I python  :  Traceback (most recent call last):
10-05 14:15:35.071 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/app/main.py", line 335, in <module>
10-05 14:15:35.071 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/app.py", line 956, in run
10-05 14:15:35.071 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/base.py", line 574, in runTouchApp
10-05 14:15:35.072 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/base.py", line 339, in mainloop
10-05 14:15:35.072 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/base.py", line 383, in idle
10-05 14:15:35.072 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/base.py", line 334, in dispatch_input
10-05 14:15:35.072 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/base.py", line 263, in post_dispatch_input
10-05 14:15:35.072 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.072 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/core/window/__init__.py", line 1682, in on_motion
10-05 14:15:35.073 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.073 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/core/window/__init__.py", line 1699, in on_touch_down
10-05 14:15:35.073 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.073 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/screenmanager.py", line 1210, in on_touch_down
10-05 14:15:35.073 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.073 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.074 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/relativelayout.py", line 306, in on_touch_down
10-05 14:15:35.074 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.074 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.074 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.074 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.074 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.075 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.075 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.075 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.075 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/widget.py", line 589, in on_touch_down
10-05 14:15:35.075 18560 18591 I python  :    File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.075 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/behaviors/button.py", line 151, in on_touch_down
10-05 14:15:35.076 18560 18591 I python  :    File "kivy/_event.pyx", line 727, in kivy._event.EventDispatcher.dispatch
10-05 14:15:35.076 18560 18591 I python  :    File "kivy/_event.pyx", line 1307, in kivy._event.EventObservers.dispatch
10-05 14:15:35.076 18560 18591 I python  :    File "kivy/_event.pyx", line 1191, in kivy._event.EventObservers._dispatch
10-05 14:15:35.076 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/lang/builder.py", line 60, in custom_callback
10-05 14:15:35.076 18560 18591 I python  :    File "/data/data/com.gnethomelinux.midistrum/files/app/midistrum.kv", line 147, in <module>
10-05 14:15:35.077 18560 18591 I python  :      on_press: app.open_settings()
10-05 14:15:35.077 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/app.py", line 1084, in open_settings
10-05 14:15:35.077 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/app.py", line 1153, in create_settings
10-05 14:15:35.077 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/app/main.py", line 315, in build_settings
10-05 14:15:35.077 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/settings.py", line 1044, in add_json_panel
10-05 14:15:35.077 18560 18591 I python  :    File "/home/vagrant/build/com.gnethomelinux.midistrum/src/.buildozer/android/platform/build-arm64-v8a/build/python-installs/midistrum/arm64-v8a/kivy/uix/settings.py", line 1064, in create_json_panel
10-05 14:15:35.078 18560 18591 I python  :  ValueError: The first element must be a list
10-05 14:15:35.078 18560 18591 I python  : Python for android ended.
```

**Comment by maxpunktezahl** [comment] 2023-10-05 22:10
Same behaviour here. Gihub Version works, fdroid not. BTW: l love the App, cause I own a Omnicord!

**Comment by guysoft** [comment] 2023-10-06 14:34
Ok I think I found the issue. There is a bug in kivy introduced 2 months ago.
I placed a PR to fix it:
https://github.com/kivy/kivy/pull/8389

I can try in the meantime to pin the version of kivy to build against (or the pr will get merged)

**Comment by guysoft** [comment] 2023-10-06 15:44
Pushed a fix to f-droid:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13813

**Comment by guysoft** [comment] 2023-10-26 08:48
Still failing, something in the container on Fdroid is building and app that is not working, still investigating.

**Comment by guysoft** [comment] 2023-10-27 18:56
So after two weeks of playing around and trying quite a few configurations I have one that works on f-droid build system.
The issue is that kivy/python4android needs very spesific versions of android and the one that is shipped with the container just doesn't work. Moreover I found that pinning the version of python, the version of kivy (not to build from master, which I actually found a regression there https://github.com/kivy/kivy/pull/8389).
The solution I have now works, but it requires compiling python 3.8.15 on the build. I tried combinations with the python 3.9.2 that is there and it just does not work.
You can see a bunch of tests I made here:
https://gitlab.com/guysoft/fdroiddata/-/commits/update-midistrum-debug?ref_type=heads

Updated here on froid and waiting for them to review it:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13813#note_32890081

**Comment by guysoft** [comment] 2023-11-01 12:03
Fix was merged, waiting for a build

**Comment by kenwud** [comment] 2023-11-01 17:33
fdroid branch settings crash here too, miui 13 android 12, ill try the GitHub release 

ah I see this seems imminently resolved can't wait to try this out

**Comment by guysoft** [comment] 2023-11-01 18:11
@kenwud wait for version 0.2.9 to be available on f-droid. It built successfully and should be available once all the other builds of different apps are done.

**Comment by guysoft** [comment] 2023-11-03 16:51
New version on f-droid uploaded, tested and works. Enjoy :)

**Closed by guysoft** 2023-11-03 16:51 UTC
